### PR TITLE
Web API Session Controller

### PR DESCRIPTION
**Pull request by gbossert**
This PR covers both #66 and #67.
When the users starts netzob with `netzob -w`, a web interface is exposed at `http://127.0.0.1:8080` while API and its Swagger UI is made available at `http://127.0.0.1:8080/api`.

### CODE REVIEW

**Comment by gbossert** [comment]
@Sygus what do you think of merging webapi into netzob core ? @otetard raised the question.

**Comment by otetard** [comment]
Before we merge this PR, we should decide or not if we merge or not the web API in Netzob core. 

In favor of merging web API:
- better integration with Netzob itself;
- no need to maintain two separate projects;
- facility to add new tests (avoid the creation of new testsuites).

In favor of keeping two separate projects:
- don’t mix totally different code (core and UI);
- don’t add web dependencies to the core project;
- keep Netzob API clean and usable.

I would vote for keeping two separate repositories, but, I’m not yet totally convinced.

Olivier;

**Comment by gbossert** [comment]
in favor of merging web API
* simpler packaging, dependencies management and installation process for endusers

In favor of keeping two separate projects
* lighter netzob-core for projects that use netzob as a dependency

**Comment by Sygus** [comment]
I clearly agree with your pros and cons.

My opinion : if we see Netzob as a library (that could be integrated into other tools), it would be sad to force Web dependencies such as Flask and graph rendering libraries (which are quite big in general). And at the beginning of Netzob API rewriting, we decided it was better to make it a library, and to focus on exposing a clear and simple API.

So... maybe we could keep the Web part separate (despite my previous approval of this PR :).

**Comment by gbossert** [comment]
Lets say with keep both projects (netzob-gui and netzob-core) separate for endusers.

Shoud we put them in the same repository but under different directories such as:
* netzob/
  * netzob.exe
  * setup.py
  * netzob-core/
    * setup.py
    * src/
    * ...
  * netzob-web/
     * setup.py
     * src/
     * ...

This way, a user or an application can refer to netzob-core  since it has its own `setup.py` file.
However, a user that wants `netzob.exe` can clone the official repository and follow the `setup.py install` process to install both netzob-core and netzob-web.
Besides, this ensures both the code AND the devel team of netzob-web and netzob-core are synchronized.

**Comment by gbossert** [comment]
Initiates a netzob web interface via a new project `netzob_web`.

To improve readability, the original `netzob` content is moved in a subdirectory also called `netzob`.
If this PR is accepted, the repository will contain the two following sub directories:

* /netzob/{README.rst, src/, ...}
* /netzob_web/{README.rst, ...}

This ensures both netzob_web and netzob core are synchronized.
We could also develop a top testing module that triggers tests execution of both netzob and netzob-web.

In the meantime, a new README.rst must be created and pushed at the repository root to explain netzob repository.
If reviewers accept this PR, I will provide the README.rst before merging.

Don't forget to test both the core and the web-interface.

**Comment by otetard** [comment]
Shouldn’t a7447d4b36b5fa5b927ead1bed50171e666be590 be squashed with the first commits of the PR (or just remove the first commits that will then be reverted)?

**Comment by gbossert** [comment]
OK, I will try to improve this PR.

**Comment by gbossert** [comment]
See new version of the PR is #71

**Pull request closed without merging**
